

version: '3'
services: 
    db:  
      image: postgres
      restart: always 
      ports: 
        - '5432:5432'
      environment: 
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - ./postgres:/var/lib/postgresql/data
      container_name: Tesloshop
    
